#!/usr/bin/bash


echo "Access Point creating script is running..."
#disable network
systemctl stop NetworkManager

airmon-ng check kill

ifconfig wlp3s0 10.0.0.1/24

ifconfig wlp3s0 10.0.0.1 netmask 255.255.255.0

route add default gw 10.0.0.1

dnsmasq -C dnsmasq.conf
hostapd hostapd.conf 

systemctl start httpd
